#!/bin/bash
# Fail early
set -e

# The directory this script is in
BASEDIR="$(readlink -f $(dirname $0))"

cd "$BASEDIR"

if [[ ! -e env ]]; then
    virtualenv -p python3 --system-site-packages env
    PIP="$BASEDIR/env/bin/pip"
    "$PIP" install -r "$BASEDIR/requirements.txt"
fi

PYTHON="$BASEDIR/env/bin/python"

"$PYTHON" -m "spc"
